import numpy as np

STEP = 0.1

INITIAL_POSITION = 1
CURRENT_POSITION = 1

RAIL_TOTAL_LENGTH = 3
RAIL_WIDTH = 0.01
RAIL_HEIGTH = 1

RAIL_RESISTIVITY = 2.65e-8 # need to find

DISTANCE_BETWEEN_RAILS = 0.02

INTERNAL_RESISTANCE = 0.5 # resistor added to thing

PROJECTILE_VELOCITY = [0, 0, 0]
PROJECTILE_MAGNETIC_FORCE = [0, 0, 0]
PROJECTILE_MASS = 0.001 #kg

CURRENT_RESISTIVITY = 0

VOLTAGE = 9
MAGNETIC_PERMEABILITY = 4e-7 * np.pi

RESISTENCES = []
CURRENTS = []
VELOCITIES = []

