import numpy as np

TIME =10
STEP = 0.05

FRICTION_COEFFICIENT = 0.3  # steel on steel, NEEDS TO BE CHANGED MAYBE


#ALL measurements in meters
INITIAL_POSITION = 0.01
CURRENT_POSITION = 0.01

RAIL_TOTAL_LENGTH = 0.20
RAIL_WIDTH = 0.005
RAIL_HEIGTH = 0.005

RAIL_RESISTIVITY = 2.65e-8 # need to measure

DISTANCE_BETWEEN_RAILS = 0.015

INTERNAL_RESISTANCE = 0.05 # resistor added to thing, can change

PROJECTILE_VELOCITY = [0, 0, 0]
PROJECTILE_MAGNETIC_FORCE = [0, 0, 0]
PROJECTILE_MASS = 0.002 #kg

CURRENT_RESISTIVITY = 0

VOLTAGE = 9
MAGNETIC_PERMEABILITY = 4e-7 * np.pi

RESISTENCES = []
CURRENTS = []
VELOCITIES = []

